/* ═══════════════════════════════════════════════════════
   TEETH DATABASE — Complete Permanent Dentition
   32 Teeth • Full anatomical data
   ═══════════════════════════════════════════════════════ */

const TEETH_DATA = {
  // ═════ MAXILLARY (UPPER) ═════
  1: { universal: 1, fdi: 18, palmer: '8└', name: 'Maxillary Right Third Molar', short: 'M3', arch: 'Maxillary', side: 'Right', type: 'Molar', class: 'molar',
    chronology: { calcification: '7–9 years', crown: '12–16 years', eruption: '17–21 years', root: '18–25 years' },
    roots: 3, canals: '3–4', shape: 'Variable, often fused' },
  2: { universal: 2, fdi: 17, palmer: '7└', name: 'Maxillary Right Second Molar', short: 'M2', arch: 'Maxillary', side: 'Right', type: 'Molar', class: 'molar',
    chronology: { calcification: '2.5–3 years', crown: '7–8 years', eruption: '12–13 years', root: '14–16 years' },
    roots: 3, canals: '3–4', shape: 'Trapezoidal (occlusal)' },
  3: { universal: 3, fdi: 16, palmer: '6└', name: 'Maxillary Right First Molar', short: 'M1', arch: 'Maxillary', side: 'Right', type: 'Molar', class: 'molar',
    chronology: { calcification: 'At birth', crown: '2.5–3 years', eruption: '6–7 years', root: '9–10 years' },
    roots: 3, canals: '3–4', shape: 'Rhomboidal (occlusal)' },
  4: { universal: 4, fdi: 15, palmer: '5└', name: 'Maxillary Right Second Premolar', short: 'P2', arch: 'Maxillary', side: 'Right', type: 'Premolar', class: 'premolar',
    chronology: { calcification: '2–2.25 years', crown: '6–7 years', eruption: '10–12 years', root: '12–14 years' },
    roots: 1, canals: '1–2', shape: 'Oval' },
  5: { universal: 5, fdi: 14, palmer: '4└', name: 'Maxillary Right First Premolar', short: 'P1', arch: 'Maxillary', side: 'Right', type: 'Premolar', class: 'premolar',
    chronology: { calcification: '1.5–1.75 years', crown: '5–6 years', eruption: '10–11 years', root: '12–13 years' },
    roots: 2, canals: 2, shape: 'Two-cusped, bifurcated root' },
  6: { universal: 6, fdi: 13, palmer: '3└', name: 'Maxillary Right Canine', short: 'C', arch: 'Maxillary', side: 'Right', type: 'Canine', class: 'canine',
    chronology: { calcification: '4–5 months', crown: '6–7 years', eruption: '11–12 years', root: '13–15 years' },
    roots: 1, canals: 1, shape: 'Single cusp, long conical root' },
  7: { universal: 7, fdi: 12, palmer: '2└', name: 'Maxillary Right Lateral Incisor', short: 'I2', arch: 'Maxillary', side: 'Right', type: 'Incisor', class: 'incisor',
    chronology: { calcification: '10–12 months', crown: '4–5 years', eruption: '8–9 years', root: '11 years' },
    roots: 1, canals: 1, shape: 'Ovoid, smaller than central' },
  8: { universal: 8, fdi: 11, palmer: '1└', name: 'Maxillary Right Central Incisor', short: 'I1', arch: 'Maxillary', side: 'Right', type: 'Incisor', class: 'incisor',
    chronology: { calcification: '3–4 months', crown: '4–5 years', eruption: '7–8 years', root: '10 years' },
    roots: 1, canals: 1, shape: 'Trapezoidal (labial), Conical root' },
  9: { universal: 9, fdi: 21, palmer: '┘1', name: 'Maxillary Left Central Incisor', short: 'I1', arch: 'Maxillary', side: 'Left', type: 'Incisor', class: 'incisor',
    chronology: { calcification: '3–4 months', crown: '4–5 years', eruption: '7–8 years', root: '10 years' },
    roots: 1, canals: 1, shape: 'Trapezoidal (labial), Conical root' },
  10: { universal: 10, fdi: 22, palmer: '┘2', name: 'Maxillary Left Lateral Incisor', short: 'I2', arch: 'Maxillary', side: 'Left', type: 'Incisor', class: 'incisor',
    chronology: { calcification: '10–12 months', crown: '4–5 years', eruption: '8–9 years', root: '11 years' },
    roots: 1, canals: 1, shape: 'Ovoid, smaller than central' },
  11: { universal: 11, fdi: 23, palmer: '┘3', name: 'Maxillary Left Canine', short: 'C', arch: 'Maxillary', side: 'Left', type: 'Canine', class: 'canine',
    chronology: { calcification: '4–5 months', crown: '6–7 years', eruption: '11–12 years', root: '13–15 years' },
    roots: 1, canals: 1, shape: 'Single cusp, long conical root' },
  12: { universal: 12, fdi: 24, palmer: '┘4', name: 'Maxillary Left First Premolar', short: 'P1', arch: 'Maxillary', side: 'Left', type: 'Premolar', class: 'premolar',
    chronology: { calcification: '1.5–1.75 years', crown: '5–6 years', eruption: '10–11 years', root: '12–13 years' },
    roots: 2, canals: 2, shape: 'Two-cusped, bifurcated root' },
  13: { universal: 13, fdi: 25, palmer: '┘5', name: 'Maxillary Left Second Premolar', short: 'P2', arch: 'Maxillary', side: 'Left', type: 'Premolar', class: 'premolar',
    chronology: { calcification: '2–2.25 years', crown: '6–7 years', eruption: '10–12 years', root: '12–14 years' },
    roots: 1, canals: '1–2', shape: 'Oval' },
  14: { universal: 14, fdi: 26, palmer: '┘6', name: 'Maxillary Left First Molar', short: 'M1', arch: 'Maxillary', side: 'Left', type: 'Molar', class: 'molar',
    chronology: { calcification: 'At birth', crown: '2.5–3 years', eruption: '6–7 years', root: '9–10 years' },
    roots: 3, canals: '3–4', shape: 'Rhomboidal (occlusal)' },
  15: { universal: 15, fdi: 27, palmer: '┘7', name: 'Maxillary Left Second Molar', short: 'M2', arch: 'Maxillary', side: 'Left', type: 'Molar', class: 'molar',
    chronology: { calcification: '2.5–3 years', crown: '7–8 years', eruption: '12–13 years', root: '14–16 years' },
    roots: 3, canals: '3–4', shape: 'Trapezoidal (occlusal)' },
  16: { universal: 16, fdi: 28, palmer: '┘8', name: 'Maxillary Left Third Molar', short: 'M3', arch: 'Maxillary', side: 'Left', type: 'Molar', class: 'molar',
    chronology: { calcification: '7–9 years', crown: '12–16 years', eruption: '17–21 years', root: '18–25 years' },
    roots: 3, canals: '3–4', shape: 'Variable, often fused' },

  // ═════ MANDIBULAR (LOWER) ═════
  17: { universal: 17, fdi: 38, palmer: '┐8', name: 'Mandibular Left Third Molar', short: 'M3', arch: 'Mandibular', side: 'Left', type: 'Molar', class: 'molar',
    chronology: { calcification: '8–10 years', crown: '12–16 years', eruption: '17–21 years', root: '18–25 years' },
    roots: 2, canals: '3–4', shape: 'Variable' },
  18: { universal: 18, fdi: 37, palmer: '┐7', name: 'Mandibular Left Second Molar', short: 'M2', arch: 'Mandibular', side: 'Left', type: 'Molar', class: 'molar',
    chronology: { calcification: '2.5–3 years', crown: '7–8 years', eruption: '11–13 years', root: '14–15 years' },
    roots: 2, canals: '3', shape: 'Rectangular (occlusal)' },
  19: { universal: 19, fdi: 36, palmer: '┐6', name: 'Mandibular Left First Molar', short: 'M1', arch: 'Mandibular', side: 'Left', type: 'Molar', class: 'molar',
    chronology: { calcification: 'At birth', crown: '2.5–3 years', eruption: '6–7 years', root: '9–10 years' },
    roots: 2, canals: '3–4', shape: 'Pentagonal (occlusal)' },
  20: { universal: 20, fdi: 35, palmer: '┐5', name: 'Mandibular Left Second Premolar', short: 'P2', arch: 'Mandibular', side: 'Left', type: 'Premolar', class: 'premolar',
    chronology: { calcification: '2.25–2.5 years', crown: '6–7 years', eruption: '11–12 years', root: '13–14 years' },
    roots: 1, canals: 1, shape: 'Two or three cusps' },
  21: { universal: 21, fdi: 34, palmer: '┐4', name: 'Mandibular Left First Premolar', short: 'P1', arch: 'Mandibular', side: 'Left', type: 'Premolar', class: 'premolar',
    chronology: { calcification: '1.75–2 years', crown: '5–6 years', eruption: '10–12 years', root: '12–13 years' },
    roots: 1, canals: 1, shape: 'Two-cusped (large buccal)' },
  22: { universal: 22, fdi: 33, palmer: '┐3', name: 'Mandibular Left Canine', short: 'C', arch: 'Mandibular', side: 'Left', type: 'Canine', class: 'canine',
    chronology: { calcification: '4–5 months', crown: '6–7 years', eruption: '9–10 years', root: '12–14 years' },
    roots: 1, canals: 1, shape: 'Single cusp, narrower than max canine' },
  23: { universal: 23, fdi: 32, palmer: '┐2', name: 'Mandibular Left Lateral Incisor', short: 'I2', arch: 'Mandibular', side: 'Left', type: 'Incisor', class: 'incisor',
    chronology: { calcification: '3–4 months', crown: '4–5 years', eruption: '7–8 years', root: '10 years' },
    roots: 1, canals: 1, shape: 'Fan-shaped, slightly wider than central' },
  24: { universal: 24, fdi: 31, palmer: '┐1', name: 'Mandibular Left Central Incisor', short: 'I1', arch: 'Mandibular', side: 'Left', type: 'Incisor', class: 'incisor',
    chronology: { calcification: '3–4 months', crown: '4–5 years', eruption: '6–7 years', root: '9 years' },
    roots: 1, canals: 1, shape: 'Smallest tooth, symmetrical' },
  25: { universal: 25, fdi: 41, palmer: '1┌', name: 'Mandibular Right Central Incisor', short: 'I1', arch: 'Mandibular', side: 'Right', type: 'Incisor', class: 'incisor',
    chronology: { calcification: '3–4 months', crown: '4–5 years', eruption: '6–7 years', root: '9 years' },
    roots: 1, canals: 1, shape: 'Smallest tooth, symmetrical' },
  26: { universal: 26, fdi: 42, palmer: '2┌', name: 'Mandibular Right Lateral Incisor', short: 'I2', arch: 'Mandibular', side: 'Right', type: 'Incisor', class: 'incisor',
    chronology: { calcification: '3–4 months', crown: '4–5 years', eruption: '7–8 years', root: '10 years' },
    roots: 1, canals: 1, shape: 'Fan-shaped, slightly wider than central' },
  27: { universal: 27, fdi: 43, palmer: '3┌', name: 'Mandibular Right Canine', short: 'C', arch: 'Mandibular', side: 'Right', type: 'Canine', class: 'canine',
    chronology: { calcification: '4–5 months', crown: '6–7 years', eruption: '9–10 years', root: '12–14 years' },
    roots: 1, canals: 1, shape: 'Single cusp, narrower than max canine' },
  28: { universal: 28, fdi: 44, palmer: '4┌', name: 'Mandibular Right First Premolar', short: 'P1', arch: 'Mandibular', side: 'Right', type: 'Premolar', class: 'premolar',
    chronology: { calcification: '1.75–2 years', crown: '5–6 years', eruption: '10–12 years', root: '12–13 years' },
    roots: 1, canals: 1, shape: 'Two-cusped (large buccal)' },
  29: { universal: 29, fdi: 45, palmer: '5┌', name: 'Mandibular Right Second Premolar', short: 'P2', arch: 'Mandibular', side: 'Right', type: 'Premolar', class: 'premolar',
    chronology: { calcification: '2.25–2.5 years', crown: '6–7 years', eruption: '11–12 years', root: '13–14 years' },
    roots: 1, canals: 1, shape: 'Two or three cusps' },
  30: { universal: 30, fdi: 46, palmer: '6┌', name: 'Mandibular Right First Molar', short: 'M1', arch: 'Mandibular', side: 'Right', type: 'Molar', class: 'molar',
    chronology: { calcification: 'At birth', crown: '2.5–3 years', eruption: '6–7 years', root: '9–10 years' },
    roots: 2, canals: '3–4', shape: 'Pentagonal (occlusal)' },
  31: { universal: 31, fdi: 47, palmer: '7┌', name: 'Mandibular Right Second Molar', short: 'M2', arch: 'Mandibular', side: 'Right', type: 'Molar', class: 'molar',
    chronology: { calcification: '2.5–3 years', crown: '7–8 years', eruption: '11–13 years', root: '14–15 years' },
    roots: 2, canals: '3', shape: 'Rectangular (occlusal)' },
  32: { universal: 32, fdi: 48, palmer: '8┌', name: 'Mandibular Right Third Molar', short: 'M3', arch: 'Mandibular', side: 'Right', type: 'Molar', class: 'molar',
    chronology: { calcification: '8–10 years', crown: '12–16 years', eruption: '17–21 years', root: '18–25 years' },
    roots: 2, canals: '3–4', shape: 'Variable' }
};

// Position layout for teeth (percentage-based positioning on the arch)
const MAX_POSITIONS = [
  { n: 1,  x: 92, y: 85 }, { n: 2,  x: 85, y: 60 }, { n: 3,  x: 78, y: 40 },
  { n: 4,  x: 70, y: 25 }, { n: 5,  x: 62, y: 15 }, { n: 6,  x: 54, y: 8 },
  { n: 7,  x: 45, y: 4 },  { n: 8,  x: 36, y: 2 },
  { n: 9,  x: 27, y: 2 },  { n: 10, x: 18, y: 4 },  { n: 11, x: 10, y: 8 },
  { n: 12, x: 4,  y: 15 }, { n: 13, x: 0,  y: 25 }, { n: 14, x: -4, y: 40 },
  { n: 15, x: -8, y: 60 }, { n: 16, x: -15, y: 85 }
];

const MAND_POSITIONS = [
  { n: 32, x: 92, y: 15 }, { n: 31, x: 85, y: 40 }, { n: 30, x: 78, y: 60 },
  { n: 29, x: 70, y: 75 }, { n: 28, x: 62, y: 85 }, { n: 27, x: 54, y: 92 },
  { n: 26, x: 45, y: 96 }, { n: 25, x: 36, y: 98 },
  { n: 24, x: 27, y: 98 }, { n: 23, x: 18, y: 96 }, { n: 22, x: 10, y: 92 },
  { n: 21, x: 4,  y: 85 }, { n: 20, x: 0,  y: 75 }, { n: 19, x: -4, y: 60 },
  { n: 18, x: -8, y: 40 }, { n: 17, x: -15, y: 15 }
];
